### ISSUE TITLE
Documentation in Wiki part of GitHub? 

### ISSUE THREAD

**Issue by gvaz151** [WavEC-Offshore-Renewables/pyTST#4]

**Comment by Nanoseb** [comment]
I am not sure what I can document more. The code is self documented through docstrings, so you can use `help(class)` or `help(class.method)` to view it's documentation. And the readme and example folders provide some examples of what can be done.

For these kind of small libraries, I tend to not use the wiki as it is not 'self' contained. Meaning that you don't get the wiki by just cloning the repo, if you rely on the wiki for documenting, then you can't work offline, can't migrate to an other git hosting provider etc. Wiki pages are useful sometimes, but for this lib, I am not sure for what.

**Comment by gvaz151** [comment]
Ok. As you wish. Case closed.

**Comment by Nanoseb** [comment]
sorry if I seem to definitive in my previous message. If you had ideas of things to document that would fit in a wiki I will be happy to add them.
